package com.purelab.utils

// Document: 30001~
fun sampleBrandsList() = listOf(
    mapOf<String, Any>("name" to "CANADEL(カナデル)"),
    mapOf<String, Any>("name" to "d プログラム"),
    mapOf<String, Any>("name" to "HAP＋R(ハップアール)"),
    mapOf<String, Any>("name" to "KANEBO"),
    mapOf<String, Any>("name" to "LANEIGE(ラネージュ)"),
    mapOf<String, Any>("name" to "NARS(ナーズ)"),
    mapOf<String, Any>("name" to "numbuzin"),
    mapOf<String, Any>("name" to "ONE BY KOSE"),
    mapOf<String, Any>("name" to "RMK"),
    mapOf<String, Any>("name" to "rom&nd"),
    mapOf<String, Any>("name" to "SHISEIDO(シセイドウ)"),
    mapOf<String, Any>("name" to "SOFINA iP"),
    mapOf<String, Any>("name" to "the SAEM"),
    mapOf<String, Any>("name" to "VT(ブイティー)"),
    mapOf<String, Any>("name" to "アクアレーベル"),
    mapOf<String, Any>("name" to "アスタリフト"),
    mapOf<String, Any>("name" to "アディクション"),
    mapOf<String, Any>("name" to "アテニア"),
    mapOf<String, Any>("name" to "アネッサ"),
    mapOf<String, Any>("name" to "アユーラ"),
    mapOf<String, Any>("name" to "アリィー"),
    mapOf<String, Any>("name" to "いつかの石けん"),
    mapOf<String, Any>("name" to "イハダ"),
    mapOf<String, Any>("name" to "イプサ"),
    mapOf<String, Any>("name" to "ヴィセ"),
    mapOf<String, Any>("name" to "エージーデオ24"),
    mapOf<String, Any>("name" to "エクセル"),
    mapOf<String, Any>("name" to "エスティ ローダー"),
    mapOf<String, Any>("name" to "エスト"),
    mapOf<String, Any>("name" to "エッセンシャル"),
    mapOf<String, Any>("name" to "エリクシール"),
    mapOf<String, Any>("name" to "オクチレモン"),
    mapOf<String, Any>("name" to "オルビス"),
    mapOf<String, Any>("name" to "キャンメイク"),
    mapOf<String, Any>("name" to "キュレル"),
    mapOf<String, Any>("name" to "クリニーク"),
    mapOf<String, Any>("name" to "クレ・ド・ポー ボーテ"),
    mapOf<String, Any>("name" to "ケイト"),
    mapOf<String, Any>("name" to "コーセー"),
    mapOf<String, Any>("name" to "コーセーコスメニエンス"),
    mapOf<String, Any>("name" to "コスメデコルテ"),
    mapOf<String, Any>("name" to "シェルクルール"),
    mapOf<String, Any>("name" to "シュウ ウエムラ"),
    mapOf<String, Any>("name" to "スイサイ"),
    mapOf<String, Any>("name" to "スノービューティー"),
    mapOf<String, Any>("name" to "セザンヌ"),
    mapOf<String, Any>("name" to "ダーマレーザー"),
    mapOf<String, Any>("name" to "タカミ"),
    mapOf<String, Any>("name" to "チャコット・コスメティクス/Chacott COSMETICS"),
    mapOf<String, Any>("name" to "ディオール"),
    mapOf<String, Any>("name" to "デオナチュレ"),
    mapOf<String, Any>("name" to "デュオ"),
    mapOf<String, Any>("name" to "ナチュリエ"),
    mapOf<String, Any>("name" to "ニベア"),
    mapOf<String, Any>("name" to "ハウスオブローゼ"),
    mapOf<String, Any>("name" to "ハク"),
    mapOf<String, Any>("name" to "ビオデルマ"),
    mapOf<String, Any>("name" to "ビフェスタ"),
    mapOf<String, Any>("name" to "ピュレア"),
    mapOf<String, Any>("name" to "ヒロインメイク"),
    mapOf<String, Any>("name" to "ファンケル"),
    mapOf<String, Any>("name" to "フジコ"),
    mapOf<String, Any>("name" to "ベネフィーク"),
    mapOf<String, Any>("name" to "マキアージュ"),
    mapOf<String, Any>("name" to "マジョリカ マジョルカ"),
    mapOf<String, Any>("name" to "ミノン"),
    mapOf<String, Any>("name" to "メラノCC"),
    mapOf<String, Any>("name" to "メルヴィータ"),
    mapOf<String, Any>("name" to "モイスチュアマイルド ホワイト"),
    mapOf<String, Any>("name" to "ラ ロッシュ ポゼ"),
    mapOf<String, Any>("name" to "ランコム"),
    mapOf<String, Any>("name" to "リファ"),
    mapOf<String, Any>("name" to "ルルルン"),
    mapOf<String, Any>("name" to "レブロン")
)