package com.purelab.utils

fun sampleBrandsList() = listOf(
    mapOf<String, Any>("brandID" to "30001","name" to "CANADEL(カナデル)"),
    mapOf<String, Any>("brandID" to "30002","name" to "d プログラム"),
    mapOf<String, Any>("brandID" to "30003","name" to "HAP＋R(ハップアール)"),
    mapOf<String, Any>("brandID" to "30004","name" to "KANEBO"),
    mapOf<String, Any>("brandID" to "30005","name" to "LANEIGE(ラネージュ)"),
    mapOf<String, Any>("brandID" to "30006","name" to "NARS(ナーズ)"),
    mapOf<String, Any>("brandID" to "30007","name" to "numbuzin"),
    mapOf<String, Any>("brandID" to "30008","name" to "ONE BY KOSE"),
    mapOf<String, Any>("brandID" to "30009","name" to "RMK"),
    mapOf<String, Any>("brandID" to "30010","name" to "rom&nd"),
    mapOf<String, Any>("brandID" to "30011","name" to "SHISEIDO(シセイドウ)"),
    mapOf<String, Any>("brandID" to "30012","name" to "SOFINA iP"),
    mapOf<String, Any>("brandID" to "30013","name" to "the SAEM"),
    mapOf<String, Any>("brandID" to "30014","name" to "VT(ブイティー)"),
    mapOf<String, Any>("brandID" to "30015","name" to "アクアレーベル"),
    mapOf<String, Any>("brandID" to "30016","name" to "アスタリフト"),
    mapOf<String, Any>("brandID" to "30017","name" to "アディクション"),
    mapOf<String, Any>("brandID" to "30018","name" to "アテニア"),
    mapOf<String, Any>("brandID" to "30019","name" to "アネッサ"),
    mapOf<String, Any>("brandID" to "30020","name" to "アユーラ"),
    mapOf<String, Any>("brandID" to "30021","name" to "アリィー"),
    mapOf<String, Any>("brandID" to "30022","name" to "いつかの石けん"),
    mapOf<String, Any>("brandID" to "30023","name" to "イハダ"),
    mapOf<String, Any>("brandID" to "30024","name" to "イプサ"),
    mapOf<String, Any>("brandID" to "30025","name" to "ヴィセ"),
    mapOf<String, Any>("brandID" to "30026","name" to "エージーデオ24"),
    mapOf<String, Any>("brandID" to "30027","name" to "エクセル"),
    mapOf<String, Any>("brandID" to "30028","name" to "エスティ ローダー"),
    mapOf<String, Any>("brandID" to "30029","name" to "エスト"),
    mapOf<String, Any>("brandID" to "30030","name" to "エッセンシャル"),
    mapOf<String, Any>("brandID" to "30031","name" to "エリクシール"),
    mapOf<String, Any>("brandID" to "30032","name" to "オクチレモン"),
    mapOf<String, Any>("brandID" to "30033","name" to "オルビス"),
    mapOf<String, Any>("brandID" to "30034","name" to "キャンメイク"),
    mapOf<String, Any>("brandID" to "30035","name" to "キュレル"),
    mapOf<String, Any>("brandID" to "30036","name" to "クリニーク"),
    mapOf<String, Any>("brandID" to "30037","name" to "クレ・ド・ポー ボーテ"),
    mapOf<String, Any>("brandID" to "30038","name" to "ケイト"),
    mapOf<String, Any>("brandID" to "30039","name" to "コーセー"),
    mapOf<String, Any>("brandID" to "30040","name" to "コーセーコスメニエンス"),
    mapOf<String, Any>("brandID" to "30041","name" to "コスメデコルテ"),
    mapOf<String, Any>("brandID" to "30042","name" to "シェルクルール"),
    mapOf<String, Any>("brandID" to "30043","name" to "シュウ ウエムラ"),
    mapOf<String, Any>("brandID" to "30044","name" to "スイサイ"),
    mapOf<String, Any>("brandID" to "30045","name" to "スノービューティー"),
    mapOf<String, Any>("brandID" to "30046","name" to "セザンヌ"),
    mapOf<String, Any>("brandID" to "30047","name" to "ダーマレーザー"),
    mapOf<String, Any>("brandID" to "30048","name" to "タカミ"),
    mapOf<String, Any>("brandID" to "30049","name" to "チャコット・コスメティクス/Chacott COSMETICS"),
    mapOf<String, Any>("brandID" to "30050","name" to "ディオール"),
    mapOf<String, Any>("brandID" to "30051","name" to "デオナチュレ"),
    mapOf<String, Any>("brandID" to "30052","name" to "デュオ"),
    mapOf<String, Any>("brandID" to "30053","name" to "ナチュリエ"),
    mapOf<String, Any>("brandID" to "30054","name" to "ニベア"),
    mapOf<String, Any>("brandID" to "30055","name" to "ハウスオブローゼ"),
    mapOf<String, Any>("brandID" to "30056","name" to "ハク"),
    mapOf<String, Any>("brandID" to "30057","name" to "ビオデルマ"),
    mapOf<String, Any>("brandID" to "30058","name" to "ビフェスタ"),
    mapOf<String, Any>("brandID" to "30059","name" to "ピュレア"),
    mapOf<String, Any>("brandID" to "30060","name" to "ヒロインメイク"),
    mapOf<String, Any>("brandID" to "30061","name" to "ファンケル"),
    mapOf<String, Any>("brandID" to "30062","name" to "フジコ"),
    mapOf<String, Any>("brandID" to "30063","name" to "ベネフィーク"),
    mapOf<String, Any>("brandID" to "30064","name" to "マキアージュ"),
    mapOf<String, Any>("brandID" to "30065","name" to "マジョリカ マジョルカ"),
    mapOf<String, Any>("brandID" to "30066","name" to "ミノン"),
    mapOf<String, Any>("brandID" to "30067","name" to "メラノCC"),
    mapOf<String, Any>("brandID" to "30068","name" to "メルヴィータ"),
    mapOf<String, Any>("brandID" to "30069","name" to "モイスチュアマイルド ホワイト"),
    mapOf<String, Any>("brandID" to "30070","name" to "ラ ロッシュ ポゼ"),
    mapOf<String, Any>("brandID" to "30071","name" to "ランコム"),
    mapOf<String, Any>("brandID" to "30072","name" to "リファ"),
    mapOf<String, Any>("brandID" to "30073","name" to "ルルルン"),
    mapOf<String, Any>("brandID" to "30074","name" to "レブロン")
)